name: prep
description: prep
author: cole
inputs:
  sopsAgeKey:
    description: 'sops age key'
    required: true
runs:
  using: composite
  steps:
    - name: setup-nix
      uses: cachix/install-nix-action@v14
      with:
        # https://github.com/NixOS/nix/commit/bcd73ebf60bb9ba6cb09f8df4366d5474c16e4a4
        # https://github.com/NixOS/nix/actions/runs/1261349488 -> https://github.com/NixOS/nix/runs/3674433924
        install_url: https://nixos-nix-install-tests.cachix.org/serve/a3xxamann3mf9s8fp7kzdfdppli2zzhi/install
        install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve --daemon
        extra_nix_config: |
          experimental-features = nix-command flakes ca-references
    # - name: gha-init
    #   id: gha-init
    #   shell: bash
    #   env:
    #     SOPS_AGE_KEY: "${{ inputs.sopsAgeKey }}"
    #   run: |
    #     set -x
    #     ./.github/setup
    #     source /run/secrets/nixup-secrets
    #     set +x; echo "::set-output name=TAILSCALE_AUTHKEY::${TAILSCALE_AUTHKEY}"; set -x
    # - name: Tailscale
    #   uses: tailscale/github-action@v1
    #   with:
    #     authkey: '${{ steps.gha-init.outputs.TAILSCALE_AUTHKEY }}'
    - name: cache-key
      id: cache-key
      shell: bash
      run: |
        echo "setting cache key"
        set -x
        echo "::set-output name=drvPath::$(nix eval --raw '.#devShells.default.inputDerivation.drvPath')"
        echo "::set-output name=outPath::$(nix eval --raw '.#devShells.default.inputDerivation.outPath')"
    - name: cache-setup
      uses: actions/cache@v2
      with:
        path: ./.nixcache/${{ steps.cache-key.outputs.outPath }}
        key: ${{ steps.cache-key.outputs.outPath }}
    - name: cache-maybe-load-shell
      shell: bash
      run: |
        set -x
        if [[ -d "./.nixcache/${{ steps.cache-key.outputs.outPath }}" ]]; then
          nix copy --no-check-sigs --from ./.nixcache/${{ steps.cache-key.outputs.outPath }} "${{ steps.cache-key.outputs.outPath }}"
          touch ./.nixcache/${{ steps.cache-key.outputs.outPath }}-loaded
        fi
    # - name: "init"
    #   shell: bash
    #   run:  .github/exec __init
    - name: cache-maybe-save-shell
      shell: bash
      run: |
        set -x
        if [[ ! -f ./.nixcache/${{ steps.cache-key.outputs.outPath }}-loaded ]]; then
          nix build -L "${{ steps.cache-key.outputs.drvPath }}"
          nix copy --no-check-sigs --to ./.nixcache/${{ steps.cache-key.outputs.outPath }} "${{ steps.cache-key.outputs.outPath }}"
        fi
